"""position attribute

Revision ID: 68032213cd21
Revises: dd5469298da2
Create Date: 2023-01-23 11:50:24.243001

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '68032213cd21'
down_revision = 'dd5469298da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('lists', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'position')
    op.drop_column('cards', 'position')
    # ### end Alembic commands ###
